### PR TITLE
End-to-end Tamr integration test

### PR DESCRIPTION
**Pull request by cassidylaidlaw**
Don't merge this yet—still working on it.

### CODE REVIEW

**Comment by cassidylaidlaw** [comment]
The integration test is now finished! This was a pain to write but I'm glad I did it in the end...

To run the integration test, use the command `mvn test -Dtest=gov.gtas.job.scheduler.TamrIT -DfailIfNoTests=false`.

The test is in the `TamrIT` class and uses a `TamrMock` instance which mocks Tamr's end of the connection. `TamrMock` uses some simple regexes to check the correctness of GTAS's messages and then responding as a real Tamr server would.

One thing I was forced to do to make the test work was to remove `optional = false` parameters from some `@OneToOne` annotations on primary key fields in various models. Since a primary key isn't optional anyways, I'm pretty sure this annotation is redundant and can be safely removed. Maybe we should check with Rob to be sure.

I planning to write one more integration test that makes sure nothing happens if `tamr.enabled` is false in the `application.properties` file.

**Comment by cassidylaidlaw** [comment]
Now I added the test for when `tamr.enabled=false` in `TamrDisabledIT`. This creates watchlist entries and loads a flight, making sure that GTAS doesn't attempt to send anything to Tamr.

**Comment by harlankadish** [comment]
Sounds like this was challenging. Thanks for sticking with it. I think it will pay-off in making the new features easier to maintain.

Could you say a little more about why "One thing I was forced to do to make the test work was to remove optional = false parameters from some @OneToOne annotations on primary key fields in various models."? Why are you sure that this constraint is enforced elsewhere?

**Comment by cassidylaidlaw** [comment]
The fields where I removed the `optional = false` from the OneToOne annotations were all primary keys. In a lot of places, primary keys are used to refer to another table. For example, the primary key of the table for `FlightPassengerCount` references the primary key for `Flight`, i.e. a `FlightPassengerCount` with ID=8 corresponds to the `Flight` with ID=8. For some reason, this `optional = false` attribute doesn't cause an issue during normal GTAS operation, but causes errors when testing within a transaction (transactions are used so any changes to the database can be "rolled back" after each test). The reason I think the `optional = false` can be dropped is because primary keys can't be null anyways. You can't make a `FlightPassengerCount` with ID=null even if you drop the `optional = false` from the `flight` attribute defined for `FlightPassengerCount`.

We'll probably have to convince Rob and the other GTAS developers that this is necessary. I spent 6-8 hours trying to figure out a way around this issue and couldn't find one. It might come down to whether they think it's better to have a Tamr integration test or this extra attribute. Another possibility is to somehow conditionally configure the database mapping differently for the Tamr integration test.

**Comment by harlankadish** [comment]
Successful `mvn clean install` but the above test command failed. I ran it as `mvn test -Dtest=gov.gtas.job.scheduler.TamrIT -DfailIfNoTests=false -e -X > /opt/repo/datatamr/integration_test.txt 2>&1` What'd I do wrong? 
[integration_test.txt](https://github.com/Datatamer/GTAS/files/4146021/integration_test.txt)

**Comment by harlankadish** [comment]
Regarding the integration test output, is the `{"passengers":[]}` below expected?
```
02:25:19.163 [main] INFO  g.g.p.tamr.TamrDerogReplaceScheduler - Checking for watchlist edits to send to Tamr...
02:25:19.240 [main] INFO  g.g.p.tamr.TamrDerogReplaceScheduler - Sending latest watchlist to Tamr.
02:25:19.401 [main] INFO  g.g.p.tamr.jms.TamrMessageSender - Sending DC.REPLACE message to Tamr.
02:25:19.402 [main] DEBUG g.g.p.tamr.jms.TamrMessageSender - {"passengers":[{"gtasId":"10","firstName":"RUBEN","middleName":null,"lastName":"THEBAULT","gender":null,"dob":"1945-01-11","documents":null,"citizenshipCountry":null,"derogId":"10"},{"gtasId":"11","firstName":"KIM","middleName":null,"lastName":"OSAYUWAME","gender":null,"dob":"1971-09-16","documents":null,"citizenshipCountry":null,"derogId":"11"},{"gtasId":"12","firstName":"ALICIA","middleName":null,"lastName":"DAVIES","gender":null,"dob":"1962-05-21","documents":null,"citizenshipCountry":null,"derogId":"12"}]}
02:25:19.486 [main] INFO  gov.gtas.job.scheduler.TamrMock - Processing DC.REPLACE message.
02:25:19.487 [main] INFO  gov.gtas.job.scheduler.TamrMock - Processed 3 derog entries. Responding with acknowledgement.
02:25:19.503 [main] DEBUG g.g.p.tamr.jms.TamrMessageReceiver - ############### Tamr data received .... ################
02:25:19.504 [main] DEBUG g.g.p.tamr.jms.TamrMessageReceiver - Message type: DC.REPLACE
02:25:19.504 [main] DEBUG g.g.p.tamr.jms.TamrMessageReceiver - Raw JSON data: {"acknowledgment":true,"error":null}
02:25:19.555 [main] INFO  g.g.p.t.TamrMessageHandlerServiceImpl - DC.REPLACE request to Tamr acknowledged
02:25:20.854 [main] INFO  gov.gtas.services.ApisMessageService - Duplicate message, message ignored. hashcode is: 8B33D7AE630CAE7B33262250E93299A7
02:25:20.871 [main] INFO  g.g.p.tamr.jms.TamrMessageSender - Sending QUERY message to Tamr.
02:25:20.871 [main] DEBUG g.g.p.tamr.jms.TamrMessageSender - {"passengers":[]}
02:25:20.886 [main] INFO  gov.gtas.job.scheduler.TamrMock - Processing QUERY message.
02:25:20.917 [main] INFO  o.h.e.j.b.internal.AbstractBatchImpl - HHH000010: On release of batch it still contained JDBC statements
02:25:20.926 [main] INFO  o.s.t.c.t.TransactionContext - Rolled back transaction for test: [DefaultTestContext@dcdfcdb testClass = TamrIT, testInstance = gov.gtas.job.scheduler.TamrIT@11541635, testMethod = testTamrIntegration@TamrIT, testException = java.lang.AssertionError, mergedContextConfiguration = [MergedContextConfiguration@6d5832db testClass = TamrIT, locations = '{}', classes = '{class gov.gtas.job.scheduler.TamrIntegrationTestConfig}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.685 s <<< FAILURE! - in gov.gtas.job.scheduler.TamrIT
[ERROR] testTamrIntegration(gov.gtas.job.scheduler.TamrIT)  Time elapsed: 4.753 s  <<< FAILURE!
```

**Comment by harlankadish** [comment]
Wait wait wait, I forgot to empty my database, didn't I? Trying that now.

**Comment by harlankadish** [comment]
Success! Lesson learned. Sorry for the chatter.

**Pull request merged**
