### PR TITLE
Set up core receiving configuration for JMS messages from Tamr

### PR DESCRIPTION
**Pull request by cassidylaidlaw**
JMS messages are received and parsed by `TamrMessageReceiver`. Then, the parsed messages are sent to one of the `TamrMessageHandlerService` methods, which will be implemented next.

Testing is complete except for `TH.CLUSTERS` and `TH.DELTAS` messages.

### CODE REVIEW

**Comment by harlankadish** [comment]
Thanks, @cassidylaidlaw ! What sort of integration with ActiveMQ should I be able to test? ("None" is fine at this point.) Can I put a message on the OutboundQueue and see something in the GTAS logs?

**Comment by cassidylaidlaw** [comment]
Yeah, you should be able to! If you send a message and then check `catalina.out` it should have some information about the message received. To see the full logging output (most of it is logged at the `DEBUG` level), you can put the following line into `gtas-parent/gtas-commons/src/main/resources/gtas_logback.xml`, next to one of the other `<logger>` tags:

    <logger name="gov.gtas.parsers.tamr" level="DEBUG" />

You have to recompile the project after this change for it to be effective.

**Comment by cassidylaidlaw** [comment]
I added the `TH.CLUSTERS` and `TH.DELTAS` examples you sent over to the tests. I think the only thing missing now is an example with the `recordErrors` key.

**Comment by harlankadish** [comment]
I can't find the new tamr.* properties in this branch, namely, the below lines from feature/add_tamr_properties. What am I doing wrong?

######### Tamr Integration #########
tamr.enabled=false
tamr.activemq.broker.url=tcp://localhost:61616

**Comment by harlankadish** [comment]
When I added those config properties, I saw the messages being received! Cool!

**Comment by cassidylaidlaw** [comment]
Great! All tests should be implemented now, so you can merge this whenever you're ready

**Comment by harlankadish** [comment]
Did you check in `record_errors_response.json`? I also receive,
`[ERROR] Tests run: 11, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.044 s <<< FAILURE! - in gov.gtas.parsers.tamr.ReceiveTamrMessagesTest
[ERROR] testRecordErrors(gov.gtas.parsers.tamr.ReceiveTamrMessagesTest)  Time elapsed: 0.038 s  <<< ERROR!
java.io.FileNotFoundException: class path resource [tamr-messages/record_errors_response.json] cannot be resolved to URL because it does not exist
	at gov.gtas.parsers.tamr.ReceiveTamrMessagesTest.testRecordErrors(ReceiveTamrMessagesTest.java:130)

[ERROR] testClustersMessage(gov.gtas.parsers.tamr.ReceiveTamrMessagesTest)  Time elapsed: 0.023 s  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException:

Unfinished stubbing detected here:
-> at gov.gtas.parsers.tamr.ReceiveTamrMessagesTest.testRecordErrors(ReceiveTamrMessagesTest.java:130)

E.g. thenReturn() may be missing.`

**Comment by cassidylaidlaw** [comment]
Oops, looks like I forgot to add that file to Git. Let me know if it works now.

**Comment by harlankadish** [comment]
Yep, will merge. Think we should delete branches after merging?

**Comment by cassidylaidlaw** [comment]
Yeah, usually for these kind of `feature/xxx` branches I delete them after merging to avoid having a bunch of random old branches lying around.

**Pull request merged**
