### PR TITLE
Handle tamrId updates in QUERY, TH.DELTAS, and TH.CLUSTERS messages

### PR DESCRIPTION
**Pull request by cassidylaidlaw**
I believe this should update the stored `tamrId` for each GTAS traveler given the data in `QUERY` history responses as well as `TH.DELTAS` and `TH.CLUSTERS` messages from Tamr. All three of these types of messages produce similar behavior and are handled by the method `TamrMessageHandlerServiceImpl.updateTamrId`. Tests are given in `UpdateTamrIdTest`. A few remaining questions are:

 * Can we test this with simulated data before Aaron is done with the code that sends the traveler data to Tamr?
 * Do `DELETE` actions in `TH.DELTAS` messages require special behavior beyond setting the `tamrId` in GTAS's database for the corresponding traveler to `null`?
 * Should we store the `version` of the `tamrId` anywhere in GTAS's database? There currently isn't a column for it, but I could add it easily.

### CODE REVIEW

**Comment by harlankadish** [comment]
I think we discussed your second and third questions on the phone. As for testing, I think it's sufficient to

1. Load a few flights into GTAS, by moving the sample APIS messages in the repo into GTAS's incoming messaging drop folder.
2. Somehow determine GTAS's record IDs for those passengers on those flights.
3. Write simulated QUERY, TH.DELTAS, and TH.CLUSTERS Tamr-responses Tamr that reference those passengers and assign them to arbitrary tamrIds. I don't think it matters for this test that the clusters make real-world sense.
4. Put those messages on the OutboundQueue for GTAS to consume.
5. Observe if the tamrIds are updated in the GTAS database.
6. Maybe observe if those passenger clusters are reflected in the passenger details in the GTAS UI?

What do you think?

**Comment by cassidylaidlaw** [comment]
That seems reasonable. Do you want me to write an integration test for that whole workflow? Or do you think it's enough to just test it manually? I already have unit tests for the specific piece I integrated here.

**Comment by cassidylaidlaw** [comment]
Okay I just tried 1-5 above and it worked correctly for QUERY, TH.DELTAS, and TH.CLUSTERS. The UI doesn't seem to associated the passengers yet, so we'll have to do some work there later. Otherwise, I think this PR should be ready to merge.

**Comment by harlankadish** [comment]
Let's hold off on the integration test. I'll create a new Trello list for "Nice-to-haves." Thanks for doing the testing!

**Pull request merged**
